from .mearge_audio import NODE_CLASS_MAPPINGS as MERGE_AUDIO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_AUDIO_DISPLAY_MAPPINGS
from .mearge_video2 import NODE_CLASS_MAPPINGS as MERGE_VIDEO2_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_VIDEO2_DISPLAY_MAPPINGS

from .edit_video import NODE_CLASS_MAPPINGS as EDIT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EDIT_DISPLAY_MAPPINGS
from .mearge_video import NODE_CLASS_MAPPINGS as MERGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_DISPLAY_MAPPINGS
from .hash_cut import NODE_CLASS_MAPPINGS as HASH_CUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as HASH_CUT_DISPLAY_MAPPINGS
from .cut_videos import NODE_CLASS_MAPPINGS as VIDEO_CUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_CUT_DISPLAY_MAPPINGS
WEB_DIRECTORY = "./web"
# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**EDIT_MAPPINGS, **MERGE_MAPPINGS, **HASH_CUT_MAPPINGS, **MERGE_AUDIO_MAPPINGS, **VIDEO_CUT_MAPPINGS, **MERGE_VIDEO2_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**EDIT_DISPLAY_MAPPINGS, **MERGE_DISPLAY_MAPPINGS, **HASH_CUT_DISPLAY_MAPPINGS, **MERGE_AUDIO_DISPLAY_MAPPINGS, **VIDEO_CUT_DISPLAY_MAPPINGS, **MERGE_VIDEO2_DISPLAY_MAPPINGS}

# 导出节点映射和web目录
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
